[project]
site_name = "frameio-kit"
site_url = "https://frameio-kit.dev"
repo_name = "billyshambrook/frameio-kit"
repo_url = "https://github.com/billyshambrook/frameio-kit"
copyright = "Copyright &copy; 2025 Billy Shambrook"
edit_uri = "edit/main/docs/"

nav = [
  { "Home" = "index.md" },
  { "Usage" = [
    { "Getting Started" = "usage/getting_started.md" },
    { "App Configuration" = "usage/app.md" },
    { "Mounting to Existing Apps" = "usage/mounting.md" },
    { "Webhooks" = "usage/webhooks.md" },
    { "Custom Actions" = "usage/custom_actions.md" },
    { "Client API" = "usage/client_api.md" },
    { "Middleware" = "usage/middleware.md" },
    { "User Authentication" = "usage/user_auth.md" },
    { "Installation System" = "usage/installation.md" },
  ] },
  { "API Reference" = "api_reference.md" },
]

[project.theme]
features = [
  "announce.dismiss",
  "content.action.edit",
  "content.action.view",
  "content.code.annotate",
  "content.code.copy",
  "content.tooltips",
  "navigation.footer",
  "navigation.instant.preview",
  "navigation.path",
  "navigation.sections",
  "navigation.tabs",
  "navigation.tabs.sticky",
  "navigation.top",
  "search.highlight",
  "search.suggest",
  "toc.follow",
]

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

# Markdown extensions
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true

[project.markdown_extensions.pymdownx.inlinehilite]

[project.markdown_extensions.admonition]

[project.markdown_extensions.pymdownx.details]

[project.markdown_extensions.pymdownx.snippets]

[project.markdown_extensions.pymdownx.superfences]

# mkdocstrings
[project.plugins.mkdocstrings.handlers.python]
paths = ["src"]

[project.plugins.mkdocstrings.handlers.python.options]
members_order = "source"
docstring_options.ignore_init_summary = true
docstring_section_style = "list"
inherited_members = true
merge_init_into_class = true
parameter_headings = true
separate_signature = true
show_root_heading = true
show_root_full_path = false
show_signature_annotations = true
show_source = false
show_symbol_type_heading = true
show_symbol_type_toc = true
signature_crossrefs = true
summary = true
show_root_toc_entry = true
